### PR TITLE
[#175412088] Allow lowercase serviceId for certain services

### PR DESCRIPTION
**Pull request by AleDore**
This PR overrides default's behaviour of `GetServiceMetadata` handler. By default every `serviceId` extracted from path param (that is in lowercase), should be transformed into an uppercase while retrieving it from cosmos. By the way, there is a service that doesn't respect this pattern, so these changes allow a case insensitive query in order to retrieve data from cosmos in any way.

### CODE REVIEW

**Comment by gunzip** [comment]
this sounds like an hack. if we'll have another serviceid which is not all-uppercase we have to remember to put it in the list.
why do we need to convert serviceid to uppercase first? what's the reason the app look for a lowercase id? 
that would be better to write them (in io-functions-admin ?) in the expected format rather than introducing fragile exceptions here. what about it?

**Comment by AleDore** [comment]
> this sounds like an hack. if we'll have another serviceid which is not all-uppercase we have to remember to put it in the list.
> that would be better to make two queries in case the uppercase version is not found (just make another query with the received serviceid)
> 
> another option is to make a case insensitive search: `WHERE StringEquals(c.serviceId, payload.serviceId, true)`

A case insensitive search could match our need but.. Is it more expensive for cosmos?

**Comment by gunzip** [comment]
> > this sounds like an hack. if we'll have another serviceid which is not all-uppercase we have to remember to put it in the list.
> > that would be better to make two queries in case the uppercase version is not found (just make another query with the received serviceid)
> > another option is to make a case insensitive search: `WHERE StringEquals(c.serviceId, payload.serviceId, true)`
> 
> A case insensitive search could match our need but.. Is it too much expensive for cosmos?

To answer this question you must check the required RSU (request charge) in the 'Query Stats' panel of cosmosdb UI (azure portal) manually triggering the query. I've done that and there's no significative increase for the case insensitive search

```
SELECT * FROM c WHERE c.serviceId = "01DVK5Y9Y09VAGSSZWK9ABQ3EB" = 2.87 RSU
SELECT * FROM c WHERE StringEquals(c.serviceId, "01DVK5Y9Y09VAGSSZWK9ABQ3EB", false) = 2.87 RSU
SELECT * FROM c WHERE StringEquals(c.serviceId, "01DVK5Y9Y09VAGSSZWK9ABQ3EB", true) = 3.44 RSU
```

we can safely use the latest query (case insensitive).

**Comment by AleDore** [comment]
> > > this sounds like an hack. if we'll have another serviceid which is not all-uppercase we have to remember to put it in the list.
> > > that would be better to make two queries in case the uppercase version is not found (just make another query with the received serviceid)
> > > another option is to make a case insensitive search: `WHERE StringEquals(c.serviceId, payload.serviceId, true)`
> > 
> > 
> > A case insensitive search could match our need but.. Is it too much expensive for cosmos?
> 
> To answer this question you must check the required RSU (request charge) in the 'Query Stats' panel of cosmosdb UI (azure portal) manually triggering the query. I've done that and there's no significative increase for the case insensitive search
> 
> ```
> SELECT * FROM c WHERE c.serviceId = "01DVK5Y9Y09VAGSSZWK9ABQ3EB" = 2.87 RSU
> SELECT * FROM c WHERE StringEquals(c.serviceId, "01DVK5Y9Y09VAGSSZWK9ABQ3EB", false) = 2.87 RSU
> SELECT * FROM c WHERE StringEquals(c.serviceId, "01DVK5Y9Y09VAGSSZWK9ABQ3EB", true) = 3.44 RSU
> ```
> 
> we can safely use the latest query (case insensitive).

Deal

**Review by gunzip — APPROVED** [review]

**Pull request merged**
